### ISSUE TITLE
Reload browser in special conditions

### ISSUE THREAD

**Issue by maximusnikulin** [Va1/browser-sync-webpack-plugin#38]
Hi there! Thanks for this good plugin. I have a question about it.
I recently found out that webpack can't reload browser when I changed html file, and save HMR reloading for JS.  
I think It can be reached with your plugin. We would write to watch html files for browser sync.
So reloading of JS, CSS is job for HMR, reloading of HTML is job for browser sync plugin.
Could we do that ??
Thanks, Max

**Comment by Va1** [comment]
hey yo!
for reloading on html changes, the easiest way would be to use [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin). instead of putting static html file in your dist, you use this plugin to render a template and put it to your dist folder automatically. besides other cool features, this just makes webpack watch for changes in the template

**Comment by maximusnikulin** [comment]
Thanks I'll try this out
