### ISSUE TITLE
Error: Cannot find module 'xmlhttprequest'

### ISSUE THREAD

**Issue by mydearxym** [Va1/browser-sync-webpack-plugin#7]
i just installl and require it 
```js
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var BrowserSyncPlugin = require('browser-sync-webpack-plugin');
```
error shows:
``` bash
$ Error: Cannot find module 'xmlhttprequest'
....
```

**Comment by mydearxym** [comment]
then i install 'xmlhttprequest'  
``` bash
$ Error: Cannot find module 'engine.io-parser'
```
where is the end ?

**Comment by Va1** [comment]
Hey!

Sorry for delayed reply. The packages you are missing are seem to be required by browser-sync itself and not by this plugin. 

Though, I did a fresh project in order to check if it works if I just install webpack, browser-sync and this plugin (+ couple of loaders) and it does work without any exceptions. 

So I suggest checking if you have all the dependencies specified in your package.json, then removing `node_modules` directory and hitting `npm install` one more time.

Regards.

**Comment by Va1** [comment]
I assume, this issue is resolved, as there're no updates. Thank you.
